### ISSUE TITLE
Question about experitment on one-shot object detection

### ISSUE THREAD

**Issue by suilin0432** [dddzg/up-detr#6]
Hi~ UP-DETR is an interesting work.
I wonder if you experimented with COCO dataset about one-shot object detection.
If you have done experiments on COCO, would you like to provide the results.
Thanks a lot~

**Comment by dddzg** [comment]
I am so sorry that due to the time and resource limitation, we just fine-tuned the model on VOC and didn't perform it on COCO. 

If you want to do, you can follow the details introduced in [One-Shot Object Detection with Co-Attention and Co-Excitation](https://arxiv.org/abs/1911.12529) (Generating target and query pairs section)

**Comment by suilin0432** [comment]
Thanks for your reply, I just wonder the random query patch detection could also have amazing enhancement for one-to-many matching. Because object queries of DETR is sparse and the VOC dataset is relative easy.

**Comment by dddzg** [comment]
If you are familar with one-shot detection setting, you can try it with UP-DETR.
As far as we observe, there is no notiable difficulty of fine-tuning UP-DETR to support one-to-many matching.
Of course, there is a potential research problem that random query patch detection only supports one-to-one matching.
